services:
  redis:
    image: redis:latest
    restart: unless-stopped
  engine:
    image: draklowell/triply-search-engine:latest
    ports:
      - "8000:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
